# Generated by Django 3.1.6 on 2021-02-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('transfered_from', models.CharField(max_length=100)),
                ('transfered_to', models.CharField(max_length=100)),
            ],
        ),
    ]
